Fix build CS0266 (casting) errors
- Tests\E2E\IntegrationTestFixtureCI.cs(449,35,449,36):
  error CS0266: Cannot implicitly convert type 'int' to
  'LoRaWan.ReceiveWindowNumber'. An explicit conversion exists (are
  you missing a cast?)

- Tests\E2E\IntegrationTestFixtureCI.cs(459,35,459,36):
  error CS0266: Cannot implicitly convert type 'int' to
  'LoRaWan.ReceiveWindowNumber'. An explicit conversion exists (are
  you missing a cast?)

- Tests\E2E\IntegrationTestFixtureCI.cs(471,35,471,36):
  error CS0266: Cannot implicitly convert type 'int' to
  'LoRaWan.ReceiveWindowNumber'. An explicit conversion exists (are
  you missing a cast?)