Feature/568 cache redesign (#904)
* cache redesign
- single point of device creation
- device refresh logic
- connection cleanup handling

* use the cache to make sure the join loader does only load a device once.

* remove unused dictionary

* cleanup
- remove custom exception and use new exception type that was added

* unit test harness

* making sure that cached join devices are updated for data messages

* add more tests

* add assert on connection manager release

* add/remove tests

* update after merge

* fix printing of SearchLogEvent

* switch to use records

* additional cache tests

* refactor for re-use

* add lastupdate test

* initial tests for the device factory

* factory tests

* typo in comment

* add JoinDeviceLoader tests

* race test

* add documentation for cache options

* fix comment formatting

* fix nested if

* DevAddr cleanup tests

* restructure the LoRaDeviceCache

* update exception for ConnectionManager duplicate registrations

* add test for double registrations

* re-use key from stack

* combine if statements

* add guard for re-registering through join update

* add test for cache reset

* remove unused code

* restructure logic in DeviceLoaderSynchronizer

* address warnings

* fix a problem with a race when loading devices

* fix build errors after merge

* remove up casts of dynamic values to string

* fix dynamic type errors

* fix unnecessary casts

* revert cast "fixes"

* Require cancellation token for "GetTwinAsync" of a device client

* Use cancellation token from scope when getting twin

* Remove empty param doc

* Add references to device info param

* Make "LoRaDeviceCacheOptions" record immutable

* Seal the records

* Make nullable directive stand out

* Reuse "LoRaDeviceCache.RegistrationCount" in "HasRegistrations"

* Use interval "TimeSpan" directly in delay

* Use patterns for null checks consistently

* Make "RefreshCacheAsync" looping obvious

* Convert cache refresh helpers into local functions

* Fix CS8852 errors

- Tests\Unit\NetworkServer\LoRaDeviceCacheTest.cs(35,13,35,36): error CS8852: Init-only property or indexer 'LoRaDeviceCacheOptions.RefreshInterval' can only be assigned in an object initializer, or on 'this' or 'base' in an instance constructor or an 'init' accessor.
- Tests\Unit\NetworkServer\LoRaDeviceCacheTest.cs(102,13,102,42): error CS8852: Init-only property or indexer 'LoRaDeviceCacheOptions.MaxUnobservedLifetime' can only be assigned in an object initializer, or on 'this' or 'base' in an instance constructor or an 'init' accessor.

* Remove unused semaphore in "DeviceLoaderSynchronizer" test

* Remove unused config in "DeviceLoaderSynchronizer" tests

* trim_trailing_whitespace = true

* Remove redundant assignment of device ownership

* Inline cache refresh helpers

* Await all cache refresh tasks before exiting on cancel

* Reuse cancellation token state to break cache refresh loop

* Use "device" consistently in "LoRaDeviceCache"

* Initialize cache fields

* fix merge issues

* remove unused method

* remove unnecessary using

* use an int rather than a list to track created devices count

* combine if

* re-use devAddr field value

* Update LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/BasicsStationNetworkServerStartup.cs

Co-authored-by: Daniele Antonio Maggio <damaggio@microsoft.com>

* remove unused ctor

Co-authored-by: Patrick Schuler <paschule@microsoft.com>
Co-authored-by: Atif Aziz <code@raboof.com>
Co-authored-by: Patrick Schuler <patrick.schuler@microsoft.com>
Co-authored-by: Daniele Antonio Maggio <damaggio@microsoft.com>